#!/usr/bin/perl

use YAML::Syck;
use Data::Dumper;

use strict;
my $old = $/;
undef $/;
open my $f,"<pastebin.yml";
my $yaml = <$f>;
close $f;
$/ = $old;
my $data = Load($yaml);;


print Dumper($data);
